locations = [
  "Aberdeen City",
  "Aberdeenshire",
  "Angus",
  "Argyll & Bute",
  "Barking and Dagenham",
  "Barnet",
  "Barnsley",
  "Bath and North East Somerset",
  "Bedford",
  "Bexley",
  "Birmingham",
  "Blackburn with Darwen",
  "Blackpool",
  "Blaenau Gwent",
  "Bolton",
  "Bournemouth",
  "Bournemouth, Christchurch and Poole",
  "Bracknell Forest",
  "Bradford",
  "Brent",
  "Bridgend",
  "Brighton and Hove",
  "Bristol, City of",
  "Bromley",
  "Buckinghamshire",
  "Bury",
  "Caerphilly",
  "Calderdale",
  "Cambridgeshire",
  "Camden",
  "Cardiff",
  "Carmarthenshire",
  "Central Bedfordshire",
  "Ceredigion",
  "City of Edinburgh",
  "City of London",
  "Clackmannanshire",
  "Comhairle nan Eilean Siar",
  "Conwy",
  "Cornwall excluding Isles of Scilly",
  "Coventry",
  "Croydon",
  "Cumbria",
  "Darlington",
  "Denbighshire",
  "Derby",
  "Derbyshire",
  "Devon",
  "Doncaster",
  "Dorset",
  "Dorset",
  "Dudley",
  "Dumfries & Galloway",
  "Dundee City",
  "Durham",
  "Ealing",
  "East Ayrshire",
  "East Cheshire",
  "East Dunbartonshire",
  "East Lothian",
  "East Renfrewshire",
  "East Riding of Yorkshire",
  "East Sussex",
  "Enfield",
  "Essex",
  "Falkirk",
  "Fife",
  "Flintshire",
  "Gateshead",
  "Glasgow City",
  "Gloucestershire",
  "Greenwich",
  "Gwynedd",
  "Hackney",
  "Halton",
  "Hammersmith and Fulham",
  "Hampshire",
  "Haringey",
  "Harrow",
  "Hartlepool",
  "Havering",
  "Herefordshire, County of",
  "Hertfordshire",
  "Highland",
  "Hillingdon",
  "Hounslow",
  "Inverclyde",
  "Isle of Anglesey",
  "Isle of Wight",
  "Isles of Scilly",
  "Islington",
  "Kensington and Chelsea",
  "Kent",
  "Kingston upon Hull, City of",
  "Kingston upon Thames",
  "Kirklees",
  "Knowsley",
  "Lambeth",
  "Lancashire",
  "Leeds",
  "Leicester",
  "Leicestershire",
  "Lewisham",
  "Lincolnshire",
  "Liverpool",
  "Luton",
  "Manchester",
  "Medway",
  "Merthyr Tydfil",
  "Merton",
  "Middlesbrough",
  "Midlothian",
  "Milton Keynes",
  "Monmouthshire",
  "Moray",
  "Neath Port Talbot",
  "Newcastle upon Tyne",
  "Newham",
  "Newport",
  "Norfolk",
  "North Ayrshire",
  "North East Lincolnshire",
  "North Lanarkshire",
  "North Lincolnshire",
  "North Northamptonshire",
  "North Somerset",
  "North Tyneside",
  "North Yorkshire",
  "Northamptonshire",
  "Northumberland",
  "Nottingham",
  "Nottinghamshire",
  "Oldham",
  "Orkney Islands",
  "Oxfordshire",
  "Pembrokeshire",
  "Perth & Kinross",
  "Peterborough",
  "Plymouth",
  "Poole",
  "Portsmouth",
  "Powys",
  "Reading",
  "Redbridge",
  "Redcar and Cleveland",
  "Renfrewshire",
  "Rhondda, Cynon, Taff",
  "Richmond upon Thames",
  "Rochdale",
  "Rotherham",
  "Rutland",
  "Salford",
  "Sandwell",
  "Scottish Borders",
  "Sefton",
  "Sheffield",
  "Shetland Islands",
  "Shropshire",
  "Slough",
  "Solihull",
  "Somerset",
  "South Ayrshire",
  "South Gloucestershire",
  "South Lanarkshire",
  "South Tyneside",
  "Southampton",
  "Southend-on-Sea",
  "Southwark",
  "St. Helens",
  "Staffordshire",
  "Stirling",
  "Stockport",
  "Stockton-on-Tees",
  "Stoke-on-Trent",
  "Suffolk",
  "Sunderland",
  "Surrey",
  "Sutton",
  "Swansea",
  "Swindon",
  "Tameside",
  "Telford and Wrekin",
  "The Vale of Glamorgan",
  "Thurrock",
  "Torbay",
  "Torfaen",
  "Tower Hamlets",
  "Trafford",
  "Wakefield",
  "Walsall",
  "Waltham Forest",
  "Wandsworth",
  "Warrington",
  "Warwickshire",
  "West Berkshire",
  "West Cheshire",
  "West Dunbartonshire",
  "West Lothian",
  "West Northamptonshire",
  "West Sussex",
  "Westminster",
  "Wigan",
  "Wiltshire",
  "Windsor and Maidenhead",
  "Wirral",
  "Wokingham",
  "Wolverhampton",
  "Worcestershire",
  "Wrexham",
  "York",
];